import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LangContext = createContext(null);

const DICT = {
  ar: {
    brand: "السوق الحر",
    "Free Market": "السوق الحر",
    English: "الإنجليزية",
    Arabic: "العربية",
    "Toggle language": "تبديل اللغة",
    admin: "الإدارة",
    dashboard: "لوحة التحكم",
    Dashboard: "لوحة التحكم",
    home: "الرئيسية",
    offers: "العروض",
    stores: "المتاجر",
    categories: "الأقسام",
    menu: "القائمة",
    search: "بحث…",
    Links: "روابط",
    About: "من نحن",
    "Contact us": "اتصل بنا",
    Jobs: "وظائف",
    Legal: "قانوني",
    Policy: "السياسة",
    Impressum: "البيانات القانونية",
    "Follow us": "تابعنا",
    Manage: "إدارة",
    Actions: "إجراءات",
    Approve: "قبول",
    Decline: "رفض",
    Reject: "رفض",
    Activate: "تفعيل",
    Deactivate: "تعطيل",
    First: "الاسم",
    Last: "الكنية",
    Phone: "الهاتف",
    Role: "الدور",
    Status: "الحالة",
    ID: "المعرف",
    Owner: "المالك",
    Price: "السعر",
    Brand: "العلامة",
    Active: "مفعل",
    Any: "أي",
    Total: "الإجمالي",
    Created: "تم الإنشاء",
    "No orders": "لا توجد طلبات",
    "Failed to load orders": "فشل تحميل الطلبات",
    "Failed to load profile": "فشل تحميل الملف الشخصي",
    "Failed to load users": "فشل تحميل المستخدمين",
    "Failed to load products": "فشل تحميل المنتجات",
    "Failed to load media": "فشل تحميل الوسائط",
    "Failed to load promotions": "فشل تحميل الترقيات",
    "Failed to load category": "فشل تحميل القسم",
    "Failed to load listings": "فشل تحميل الإعلانات",
    "Failed to load listing": "فشل تحميل الإعلان",
    "Failed to load order": "فشل تحميل الطلب",
    "Failed to start chat": "فشل بدء المحادثة",
    "Failed to send offer": "فشل إرسال العرض",
    "Failed to start checkout": "فشل بدء الدفع",
    refresh: "تحديث",
    addNew: "إضافة جديد",
    create: "إنشاء",
    cancel: "إلغاء",
    save: "حفظ",
    delete: "حذف",
    Edit: "تعديل",
    noItems: "لا توجد عناصر",
    cart: "السلة",
    profile: "الملف الشخصي",
    signin: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    Messages: "الرسائل",
    "First name": "الاسم الأول",
    "Last name": "الكنية",
    Password: "كلمة المرور",
    "Create account": "إنشاء حساب",
    "Already have an account?": "لديك حساب بالفعل؟",
    or: "أو",
    "Continue with Google": "المتابعة عبر جوجل",
    "No account?": "ليس لديك حساب؟",
    "Create one": "أنشئ واحداً",
    "Account created": "تم إنشاء الحساب",
    "Signup failed": "فشل التسجيل",
    "Login failed": "فشل تسجيل الدخول",
    "Signed in": "تم تسجيل الدخول",
    "Logged out": "تم تسجيل الخروج",
    Saved: "تم الحفظ",
    "Account saved": "تم حفظ الحساب",
    "Profile saved": "تم حفظ الملف الشخصي",
    "Save failed": "فشل الحفظ",
    "Update failed": "فشل التحديث",
    "Email and password are required": "البريد وكلمة المرور مطلوبة",
    electronics: "الإلكترونيات",
    computers: "الحواسيب",
    books: "الكتب",
    games: "الألعاب",
    fashion: "الأزياء",
    listings: "الإعلانات",
    sell: "بيع",
    new: "جديد",
    used: "مستعمل",
    refurbished: "مجدّد",
    "Min price": "السعر الأدنى",
    "Max price": "السعر الأقصى",
    Sort: "ترتيب",
    Apply: "تطبيق",
    Reset: "إعادة ضبط",
    Prev: "السابق",
    Next: "التالي",
    Clear: "مسح",
    "More filters": "المزيد من الفلاتر",
    "Hide more": "إخفاء المزيد",
    Newest: "الأحدث",
    "Price ↑": "السعر ↑",
    "Price ↓": "السعر ↓",
    Popular: "الأكثر مشاهدة",

    // Common UI + forms
    Name: "الاسم",
    Email: "البريد الإلكتروني",
    Phone: "الهاتف",
    Color: "اللون",
    Size: "المقاس",
    Material: "المادة",
    Storage: "سعة التخزين",
    "RAM (GB)": "الذاكرة (GB)",
    "Screen Size (in)": "حجم الشاشة (بوصة)",
    CPU: "المعالج",
    "Camera (MP)": "الكاميرا (ميغابيكسل)",
    Viscosity: "اللزوجة",
    "Oil Type": "نوع الزيت",
    "Bulb Type": "نوع المصباح",
    "Light Type": "نوع الضوء",
    "Tire Width": "عرض الإطار",
    "Tire Profile": "ارتفاع الإطار",
    "Rim Diameter": "قطر الجنط",
    "Energy Rating": "تصنيف الطاقة",
    Capacity: "السعة",
    "Power (W)": "القدرة (واط)",
    Submit: "إرسال",
    Country: "البلد",
    City: "المدينة",
    Address: "العنوان",
    SKU: "رمز المنتج",
    "Street / Building": "الشارع / المبنى",
    Select: "اختر",
    Cash: "نقداً",
    "Bank Transfer": "حوالة بنكية",
    "Online Payment": "دفع إلكتروني",
    Invoice: "فاتورة",
    Provider: "المزود",
    "Txn ID": "معرف العملية",
    Amount: "المبلغ",
    Currency: "العملة",
    "Captured At": "تاريخ التحصيل",
    Order: "الطلب",
    "Failed to send": "فشل الإرسال",
    Payments: "المدفوعات",

    // Partner page
    "Become a Partner": "كن شريكاً",
    "Partner with us": "كن شريكاً معنا",
    "Business Field": "مجال العمل",
    "Shipping Options": "خيارات الشحن",
    "Preferred Payments": "طرق الدفع المفضلة",
    Message: "رسالتك",
    "Fashion & Apparel": "الأزياء والملابس",
    "Electronics": "الإلكترونيات",
    "Computers": "الحواسيب",
    "Mobile & Accessories": "الهواتف وإكسسواراتها",
    "Automotive": "مركبات",
    "Grocery": "البقالة",
    "Health & Beauty": "الصحة والجمال",
    "Home & Garden": "المنزل والحديقة",
    "Furniture": "الأثاث",
    "Appliances": "الأجهزة المنزلية",
    "Books & Media": "الكتب والوسائط",
    "Baby": "الرضّع",
    "Pet Supplies": "مستلزمات الحيوانات",
    "Office & Stationery": "مكتبية وقرطاسية",
    "Toys & Games": "الألعاب",
    "Sports & Outdoors": "الرياضة والهواء الطلق",
    "Jewelry & Accessories": "المجوهرات والإكسسوارات",
    "Cosmetics & Personal Care": "التجميل والعناية الشخصية",
    "Pharmacy": "صيدلية",
    "Bakery": "مخبوزات",
    "Restaurant / Food Service": "مطاعم / خدمات الطعام",
    "Industrial & Tools": "الصناعي والأدوات",
    "Hardware": "معدات وأدوات",

    // Admin/menus
    Users: "المستخدمون",
    Stores: "المتاجر",
    Products: "المنتجات",
    ManageProducts: "إدارة المنتجات",
    ManageCategories: "إدارة الأقسام",
    ManageCollectionItems: "إدارة عناصر المجموعات",
    ManageCollections: "إدارة المجموعات",
    "Hide sidebar": "إخفاء الشريط الجانبي",
    "Show sidebar": "إظهار الشريط الجانبي",
    ManageMedia: "إدارة الوسائط",
    ManageListings: "إدارة الإعلانات",
    ManageListingOffers: "عروض الإعلانات",
    ManageListingPromotions: "ترقيات الإعلانات",
    ManageReports: "إدارة البلاغات",
    Categories: "الأقسام",
    Listings: "الإعلانات",
    Reports: "البلاغات",
    "No reports": "لا توجد بلاغات",
    Media: "الوسائط",
    "Partner Requests": "طلبات الشراكة",
    "Join Request": "طلب انضمام",
    "Admin Management": "إدارة المشرف",
    "Merchant Management": "إدارة التاجر",
    "Store Management": "إدارة المتجر",
    "Store Items": "عناصر المتجر",
    Shipping: "الشحن",
    Pickup: "الاستلام",
    Payment: "الدفع",
    Reason: "السبب",
    Details: "التفاصيل",
    Invoices: "الفواتير",
    Assets: "الوسائط",
    "Admin note (optional)": "ملاحظة المشرف (اختياري)",
    "decision note": "ملاحظة القرار",
    // Common table headers/labels
    Type: "النوع",
    URL: "الرابط",
    Product: "المنتج",
    Variant: "المتغير",
    Listing: "الإعلان",
    Buyer: "المشتري",
    Amount: "المبلغ",
    Any: "أي",
    open: "مفتوح",
    closed: "مغلق",
    accepted: "مقبول",
    declined: "مرفوض",
    active: "نشط",
    expired: "منتهي",
    cancelled: "ملغى",
    "Request Help": "طلب المساعدة",
    "No results": "لا نتائج",
    Overview: "نظرة عامة",
    "My Orders": "طلباتي",
    "My Listings": "إعلاناتي",
    "Create a Listing": "إنشاء إعلان",
    Account: "الحساب",
    Search: "بحث",
    "No listings": "لا توجد إعلانات",
    "No products": "لا توجد منتجات",
    Updated: "تم التحديث",
    Expired: "منتهي",
    Cancelled: "ملغي",
    "New Store": "متجر جديد",
    "Create Store": "إنشاء متجر",
    "Store creation help": "عيّن الحالة إلى \"نشط\" عند جاهزية المتجر. اترك السبيكة فارغة لتوليدها تلقائياً من الاسم.",
    "Owner User ID": "معرف مستخدم المالك",
    Slug: "السبيكة",
    "auto from Name if empty": "تلقائياً من الاسم إذا كان فارغاً",
    "Invoice Email": "بريد الفواتير",
    "Auto Invoice": "فاتورة تلقائية",
    Suspend: "تعليق",
    Done: "تم",

    // Listing create page
    "Create Listing": "إنشاء إعلان",
    Title: "العنوان",
    Description: "الوصف",
    Category: "القسم",
    Price: "السعر",
    Currency: "العملة",
    Condition: "الحالة",
    Negotiable: "قابل للتفاوض",
    "Allow online checkout": "السماح بالدفع عبر الإنترنت",
    "Set map coordinates (optional)": "تعيين إحداثيات الخريطة (اختياري)",
    Latitude: "خط العرض",
    Longitude: "خط الطول",
    Expiry: "انتهاء",
    Never: "أبداً",
    "Choose date": "اختر التاريخ",
    "Expires at": "ينتهي في",
    "Saving…": "جارٍ الحفظ…",
    Create: "إنشاء",
    None: "بدون",
    "Failed to load categories": "فشل تحميل الأقسام",
    "Title is required": "العنوان مطلوب",
    "Valid price is required": "السعر الصحيح مطلوب",
    "Listing created": "تم إنشاء الإعلان",
    "Create listing failed": "فشل إنشاء الإعلان",
    "e.g. iPhone 12 128GB": "مثال: iPhone 12 128GB",
    "Condition, what’s included, pickup/shipping details…": "الحالة، ما هو المرفق، تفاصيل الاستلام/الشحن…",
    "e.g. 33.513": "مثال: 33.513",
    "e.g. 36.292": "مثال: 36.292",
    Subcategory: "التصنيف الفرعي",
    "Please select a subcategory": "يرجى اختيار تصنيف فرعي",

    // Store management pages
    Logo: "الشعار",
    Cover: "الغلاف",
    "Upload Logo": "رفع الشعار",
    "Upload Cover": "رفع الغلاف",
    "Enable Shipping": "تفعيل الشحن",
    "Enable Pickup": "تفعيل الاستلام",
    "Pickup Details": "تفاصيل الاستلام",
    "Failed to load": "فشل التحميل",
    "Failed to save": "فشل الحفظ",
    "Create failed": "فشل الإنشاء",
    "Upload failed": "فشل الرفع",
    "Delete failed": "فشل الحذف",
    "Loading…": "جارٍ التحميل…",
    "Add Product": "إضافة منتج",
    "Add Image": "إضافة صورة",
    "Uploading…": "جارٍ الرفع…",
    "Delete": "حذف",
    "Delete product?": "حذف المنتج؟",
    "Delete offer?": "حذف العرض؟",
    Offers: "العروض",
    Product: "المنتج",
    Stock: "المخزون",
    "Add Offer": "إضافة عرض",
    "Original Price": "السعر الأصلي",
    Discount: "الخصم",
    "Final Price": "السعر النهائي",
    "No offers": "لا توجد عروض",
    "Select product": "اختر المنتج",
    "Store": "متجر",
    "root": "— جذر —",
    "Fields JSON help": "الحقول (JSON: { \"filters\": { \"fields\": [...] } })",
    "Add Category": "إضافة قسم",
    "No categories": "لا توجد أقسام",
    Parent: "فهرس",
    Subject: "الموضوع",
    Send: "إرسال",
    Sent: "تم الإرسال",
    Help: "المساعدة",
    "Invoices helper text": "نظرة عامة على الفواتير والمدفوعات متاحة في لوحة الإدارة. لطلب كشف شهري أو مشاكل الفواتير، استخدم طلب المساعدة للتواصل مع الإدارة.",

    // Page titles for store sections
    "Store Products": "منتجات المتجر",
    "Store Categories": "أقسام المتجر",
    "Store Offers": "عروض المتجر",
    "Store Shipping": "شحن المتجر",
    "Store Payment": "مدفوعات المتجر",
    "Store Invoices": "فواتير المتجر",
    "Store Assets": "وسائط المتجر",
    "Store Help": "مساعدة المتجر",
    // Manage Categories UI
    "New Category": "قسم جديد",
    "Name (EN)": "الاسم (إنجليزي)",
    "Name (AR)": "الاسم (عربي)",
    Parent: "فهرس",
    Position: "الترتيب",
    "This cannot be undone.": "لا يمكن التراجع عن ذلك.",
    "Category deleted": "تم حذف القسم",
    "Create category": "إنشاء قسم",
    "Saving…": "جارٍ الحفظ…",
    "— none —": "— لا يوجد —",
    "auto if blank": "تلقائي إذا كان فارغاً",
    "id, name, slug…": "المعرف، الاسم، السبيكة…",
    // Merchant quick actions
    "Manage Offers": "إدارة العروض",
    "Manage Shipping": "إدارة الشحن",
    "Manage Pickup": "إدارة الاستلام",
    "Manage Payment": "إدارة الدفع",

    // Admin dashboard KPI keys
    users: "المستخدمون",
    stores: "المتاجر",
    products: "المنتجات",
    listings: "الإعلانات",
    reportsOpen: "بلاغات مفتوحة",
    payoutsPending: "دفعات معلّقة",
    reviewed: "تمت المراجعة",
    actioned: "تم اتخاذ إجراء",
    "Mark reviewed": "وضع كمراجَع",
    "Mark actioned": "وضع كمُعالَج",

    // Listing detail page
    "Added to favorites": "أُضيف إلى المفضلة",
    "Removed from favorites": "أُزيل من المفضلة",
    "This is your listing": "هذا إعلانك",
    "Thread started": "تم بدء المحادثة",
    "Enter a valid amount": "أدخل مبلغاً صالحاً",
    "Offer sent": "تم إرسال العرض",
    "Checkout disabled for this listing": "الدفع معطل لهذا الإعلان",
    "Listing not available": "الإعلان غير متاح",
    "Buy Now": "اشترِ الآن",
    "Make Offer": "قدّم عرضاً",
    "Message Seller": "أرسل رسالة للبائع",
    "You are the owner": "أنت المالك",
    "Send Offer": "إرسال عرض",
    "Amount": "المبلغ",
    "Message (optional)": "رسالة (اختياري)",
    Cancel: "إلغاء",
    Send: "إرسال",
    Favorite: "مفضلة",
    "No media": "لا توجد وسائط",
    "Not found": "غير موجود",
    "Purchase initiated": "تم بدء عملية الشراء",
    Back: "رجوع",
    "Display name": "اسم العرض",
    "Avatar URL": "رابط الصورة الشخصية",
    Bio: "نبذة",
    "Failed to save account": "فشل حفظ الحساب",
    "Failed to save profile": "فشل حفظ الملف الشخصي",
    "Failed to load your profile": "فشل تحميل ملفك الشخصي",
  },
  en: {
    brand: "Free Market",
    "Free Market": "Free Market",
    English: "English",
    Arabic: "Arabic",
    "Toggle language": "Toggle language",
    admin: "Admin",
    dashboard: "Dashboard",
    Dashboard: "Dashboard",
    home: "Home",
    offers: "Offers",
    stores: "Stores",
    categories: "Categories",
    menu: "Menu",
    search: "Search…",
    Links: "Links",
    About: "About",
    "Contact us": "Contact us",
    Jobs: "Jobs",
    Legal: "Legal",
    Policy: "Policy",
    Impressum: "Impressum",
    "Follow us": "Follow us",
    Manage: "Manage",
    Actions: "Actions",
    Approve: "Approve",
    Decline: "Decline",
    Reject: "Reject",
    Activate: "Activate",
    Deactivate: "Deactivate",
    First: "First",
    Last: "Last",
    Phone: "Phone",
    Role: "Role",
    Status: "Status",
    refresh: "Refresh",
    addNew: "Add new",
    create: "Create",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    Edit: "Edit",
    noItems: "No items",
    cart: "Cart",
    profile: "Profile",
    signin: "Sign in",
    signup: "Sign up",
    logout: "Log out",
    ID: "ID",
    Owner: "Owner",
    Price: "Price",
    Brand: "Brand",
    Active: "Active",
    Any: "Any",
    Total: "Total",
    Created: "Created",
    "No orders": "No orders",
    "Failed to load orders": "Failed to load orders",
    "Failed to load profile": "Failed to load profile",
    "Failed to load users": "Failed to load users",
    "Failed to load products": "Failed to load products",
    "Failed to load media": "Failed to load media",
    "Failed to load promotions": "Failed to load promotions",
    "Failed to load category": "Failed to load category",
    "Failed to load listings": "Failed to load listings",
    "Failed to load listing": "Failed to load listing",
    "Failed to load order": "Failed to load order",
    "Failed to start chat": "Failed to start chat",
    "Failed to send offer": "Failed to send offer",
    "Failed to start checkout": "Failed to start checkout",
    "First name": "First name",
    "Last name": "Last name",
    Password: "Password",
    "Create account": "Create account",
    "Already have an account?": "Already have an account?",
    or: "or",
    "Continue with Google": "Continue with Google",
    "No account?": "No account?",
    "Create one": "Create one",
    "Account created": "Account created",
    "Signup failed": "Signup failed",
    "Login failed": "Login failed",
    "Signed in": "Signed in",
    "Logged out": "Logged out",
    Saved: "Saved",
    "Account saved": "Account saved",
    "Profile saved": "Profile saved",
    "Save failed": "Save failed",
    "Update failed": "Update failed",
    "Email and password are required": "Email and password are required",
    electronics: "Electronics",
    computers: "Computers",
    books: "Books",
    games: "Games",
    fashion: "Fashion",
    listings: "Listings",
    sell: "Sell",
    new: "New",
    used: "Used",
    refurbished: "Refurbished",
    "Min price": "Min price",
    "Max price": "Max price",
    Sort: "Sort",
    Apply: "Apply",
    Reset: "Reset",
    Prev: "Prev",
    Next: "Next",
    Clear: "Clear",
    "More filters": "More filters",
    "Hide more": "Hide more",
    Newest: "Newest",
    "Price ↑": "Price ↑",
    "Price ↓": "Price ↓",
    Popular: "Popular",

    // Common UI + forms
    Name: "Name",
    Email: "Email",
    Phone: "Phone",
    Color: "Color",
    Size: "Size",
    Material: "Material",
    Storage: "Storage",
    "RAM (GB)": "RAM (GB)",
    "Screen Size (in)": "Screen Size (in)",
    CPU: "CPU",
    "Camera (MP)": "Camera (MP)",
    Viscosity: "Viscosity",
    "Oil Type": "Oil Type",
    "Bulb Type": "Bulb Type",
    "Light Type": "Light Type",
    "Tire Width": "Tire Width",
    "Tire Profile": "Tire Profile",
    "Rim Diameter": "Rim Diameter",
    "Energy Rating": "Energy Rating",
    Capacity: "Capacity",
    "Power (W)": "Power (W)",
    Submit: "Submit",
    Country: "Country",
    City: "City",
    Address: "Address",
    SKU: "SKU",
    "Street / Building": "Street / Building",
    Select: "Select",
    Cash: "Cash",
    "Bank Transfer": "Bank Transfer",
    "Online Payment": "Online Payment",
    Invoice: "Invoice",
    Provider: "Provider",
    "Txn ID": "Txn ID",
    Amount: "Amount",
    Currency: "Currency",
    "Captured At": "Captured At",
    Order: "Order",
    "Failed to send": "Failed to send",
    Payments: "Payments",

    // Partner page
    "Become a Partner": "Become a Partner",
    "Partner with us": "Partner with us",
    "Business Field": "Business Field",
    "Shipping Options": "Shipping Options",
    "Preferred Payments": "Preferred Payments",
    Message: "Message",
    "Fashion & Apparel": "Fashion & Apparel",
    "Electronics": "Electronics",
    "Computers": "Computers",
    "Mobile & Accessories": "Mobile & Accessories",
    "Automotive": "Automotive",
    "Grocery": "Grocery",
    "Health & Beauty": "Health & Beauty",
    "Home & Garden": "Home & Garden",
    "Furniture": "Furniture",
    "Appliances": "Appliances",
    "Books & Media": "Books & Media",
    "Baby": "Baby",
    "Pet Supplies": "Pet Supplies",
    "Office & Stationery": "Office & Stationery",
    "Toys & Games": "Toys & Games",
    "Sports & Outdoors": "Sports & Outdoors",
    "Jewelry & Accessories": "Jewelry & Accessories",
    "Cosmetics & Personal Care": "Cosmetics & Personal Care",
    "Pharmacy": "Pharmacy",
    "Bakery": "Bakery",
    "Restaurant / Food Service": "Restaurant / Food Service",
    "Industrial & Tools": "Industrial & Tools",
    "Hardware": "Hardware",

    // Admin/menus
    Users: "Users",
    Stores: "Stores",
    Products: "Products",
    ManageProducts: "Manage Products",
    ManageCategories: "Manage Categories",
    ManageCollections: "Manage Collections",    
    ManageCollectionItems: "Manage Collection Items", 
    "Hide sidebar": "Hide sidebar",
    "Show sidebar": "Show sidebar",
    ManageMedia: "Manage Media",
    ManageListings: "Manage Listings",
    ManageListingOffers: "Manage Listing Offers",
    ManageListingPromotions: "Manage Listing Promotions",
    ManageReports: "Manage Reports",
    Categories: "Categories",
    Listings: "Listings",
    Reports: "Reports",
    "No reports": "No reports",
    Media: "Media",
    "Partner Requests": "Partner Requests",
    "Join Request": "Join Request",
    "Admin Management": "Admin Management",
    "Merchant Management": "Merchant Management",
    "Store Management": "Store Management",
    "Store Items": "Store Items",
    Shipping: "Shipping",
    Pickup: "Pickup",
    Payment: "Payment",
    Reason: "Reason",
    Details: "Details",
    Invoices: "Invoices",
    Assets: "Assets",
    "Admin note (optional)": "Admin note (optional)",
    "decision note": "decision note",
    // Common table headers/labels
    Type: "Type",
    URL: "URL",
    Product: "Product",
    Variant: "Variant",
    Listing: "Listing",
    Buyer: "Buyer",
    Amount: "Amount",
    Any: "Any",
    open: "Open",
    closed: "Closed",
    accepted: "Accepted",
    declined: "Declined",
    active: "Active",
    expired: "Expired",
    cancelled: "Cancelled",
    "Request Help": "Request Help",
    "No results": "No results",
    Overview: "Overview",
    "My Orders": "My Orders",
    "My Listings": "My Listings",
    "Create a Listing": "Create a Listing",
    Account: "Account",
    Search: "Search",
    "No listings": "No listings",
    "No products": "No products",
    Updated: "Updated",
    Expired: "Expired",
    Cancelled: "Cancelled",
    "New Store": "New Store",
    "Create Store": "Create Store",
    "Store creation help": "Set Status to \"active\" when the store is ready to go live. Leave Slug empty to auto-generate it from the Name.",
    "Owner User ID": "Owner User ID",
    Slug: "Slug",
    "auto from Name if empty": "auto from Name if empty",
    "Invoice Email": "Invoice Email",
    "Auto Invoice": "Auto Invoice",
    Suspend: "Suspend",
    Done: "Done",

    // Listing create page
    "Create Listing": "Create Listing",
    Title: "Title",
    Description: "Description",
    Category: "Category",
    Price: "Price",
    Currency: "Currency",
    Condition: "Condition",
    Negotiable: "Negotiable",
    "Allow online checkout": "Allow online checkout",
    "Set map coordinates (optional)": "Set map coordinates (optional)",
    Latitude: "Latitude",
    Longitude: "Longitude",
    Expiry: "Expiry",
    Never: "Never",
    "Choose date": "Choose date",
    "Expires at": "Expires at",
    "Saving…": "Saving…",
    Create: "Create",
    None: "None",
    "Failed to load categories": "Failed to load categories",
    "Title is required": "Title is required",
    "Valid price is required": "Valid price is required",
    "Listing created": "Listing created",
    "Create listing failed": "Create listing failed",
    "e.g. iPhone 12 128GB": "e.g. iPhone 12 128GB",
    "Condition, what’s included, pickup/shipping details…": "Condition, what’s included, pickup/shipping details…",
    "e.g. 33.513": "e.g. 33.513",
    "e.g. 36.292": "e.g. 36.292",
    Subcategory: "Subcategory",
    "Please select a subcategory": "Please select a subcategory",

    // Store management pages
    Logo: "Logo",
    Cover: "Cover",
    "Upload Logo": "Upload Logo",
    "Upload Cover": "Upload Cover",
    "Enable Shipping": "Enable Shipping",
    "Enable Pickup": "Enable Pickup",
    "Pickup Details": "Pickup Details",
    "Failed to load": "Failed to load",
    "Failed to save": "Failed to save",
    "Create failed": "Create failed",
    "Upload failed": "Upload failed",
    "Delete failed": "Delete failed",
    "Loading…": "Loading…",
    "Add Product": "Add Product",
    "Add Image": "Add Image",
    "Uploading…": "Uploading…",
    "Delete": "Delete",
    "Delete product?": "Delete product?",
    "Delete offer?": "Delete offer?",
    Offers: "Offers",
    Product: "Product",
    Stock: "Stock",
    "Add Offer": "Add Offer",
    "Original Price": "Original Price",
    Discount: "Discount",
    "Final Price": "Final Price",
    "No offers": "No offers",
    "Select product": "Select product",
    "Store": "Store",
    "root": "— root —",
    "Fields JSON help": "Fields (JSON: { \"filters\": { \"fields\": [...] } })",
    "Add Category": "Add Category",
    "No categories": "No categories",
    Parent: "Parent",
    Subject: "Subject",
    Send: "Send",
    Sent: "Sent",
    Help: "Help",
    "Invoices helper text": "Invoices and payments overview is available in Admin. For a monthly statement or invoice issues, use Request Help to contact admin.",

    // Page titles for store sections
    "Store Products": "Store Products",
    "Store Categories": "Store Categories",
    "Store Offers": "Store Offers",
    "Store Shipping": "Store Shipping",
    "Store Payment": "Store Payment",
    "Store Invoices": "Store Invoices",
    "Store Assets": "Store Assets",
    "Store Help": "Store Help",
    // Manage Categories UI
    "New Category": "New Category",
    "Name (EN)": "Name (EN)",
    "Name (AR)": "Name (AR)",
    Parent: "Parent",
    Position: "Position",
    "This cannot be undone.": "This cannot be undone.",
    "Category deleted": "Category deleted",
    "Create category": "Create category",
    "Saving…": "Saving…",
    "— none —": "— none —",
    "auto if blank": "auto if blank",
    "id, name, slug…": "id, name, slug…",
    // Merchant quick actions
    "Manage Offers": "Manage Offers",
    "Manage Shipping": "Manage Shipping",
    "Manage Pickup": "Manage Pickup",
    "Manage Payment": "Manage Payment",

    // Admin dashboard KPI keys
    users: "Users",
    stores: "Stores",
    products: "Products",
    listings: "Listings",
    reportsOpen: "Open reports",
    payoutsPending: "Pending payouts",
    reviewed: "Reviewed",
    actioned: "Actioned",
    "Mark reviewed": "Mark reviewed",
    "Mark actioned": "Mark actioned",

    // Listing detail page
    "Added to favorites": "Added to favorites",
    "Removed from favorites": "Removed from favorites",
    "This is your listing": "This is your listing",
    "Thread started": "Thread started",
    "Enter a valid amount": "Enter a valid amount",
    "Offer sent": "Offer sent",
    "Checkout disabled for this listing": "Checkout disabled for this listing",
    "Listing not available": "Listing not available",
    "Buy Now": "Buy Now",
    "Make Offer": "Make Offer",
    "Message Seller": "Message Seller",
    "You are the owner": "You are the owner",
    "Send Offer": "Send Offer",
    "Amount": "Amount",
    "Message (optional)": "Message (optional)",
    Cancel: "Cancel",
    Send: "Send",
    Favorite: "Favorite",
    "No media": "No media",
    "Not found": "Not found",
    "Purchase initiated": "Purchase initiated",
    Back: "Back",
    "Display name": "Display name",
    "Avatar URL": "Avatar URL",
    Bio: "Bio",
    "Failed to save account": "Failed to save account",
    "Failed to save profile": "Failed to save profile",
    "Failed to load your profile": "Failed to load your profile",
  },
};

function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ar");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    const isAr = lang === "ar";
    const html = document.documentElement;
    html.setAttribute("lang", lang);
    html.setAttribute("dir", isAr ? "rtl" : "ltr");
  }, [lang]);

  const t = useMemo(() => {
    const table = DICT[lang] || DICT.ar;
    return (key) => table[key] ?? key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
export default LangProvider;
